#include "ws2811M0f.h"

void ws2811M0f(int BSRR, int BS, int BR,int RGB){
    asm volatile (\
        "mov r5,#0x18\n\t"
        "next: str %[bit_s],[%[addr]] \n\t"
        "@bl tenD\n\t"
    	"NOP\n\t"
    	"NOP\n\t"
    	"NOP\n\t"
    	"NOP\n\t"
    	"NOP\n\t"
        "lsl %[rgb],#1\n\t"
        "bcc clear\n\t"
        "bl tenD\n\t"
        "NOP\n\t"
        "NOP\n\t"
        "NOP\n\t"
        "NOP\n\t"
        "NOP\n\t"
    	"NOP\n\t"
    	"NOP\n\t"
        "clear: str %[bit_c],[%[addr]]\n\t"
        "bl tenD\n\t"
        "NOP\n\t"
        "NOP\n\t"
        "NOP\n\t"
    	"NOP\n\t"
    	"NOP\n\t"
    	"NOP\n\t"
    	"NOP\n\t"
        "bcs end\n\t"
    	"bl tenD\n\t"
        "NOP\n\t"
    	"NOP\n\t"
    	"NOP\n\t"
    	"NOP\n\t"
    	"NOP\n\t"
        "NOP\n\t"
    	"NOP\n\t"
        "end: NOP\n\t"
        "sub r5,r5,#1\n\t"
        "BNE next\n\t"
        "B finish\n\t"
        "tenD: NOP\n\t"
        "NOP\n\t"
        "NOP\n\t"
        "BX lr\n\t"
        "finish: NOP"
        :\
        :[rgb] "r" (RGB),[addr] "r" (BSRR), [bit_s] "r" (BS), [bit_c] "r" (BR)
        :"memory","cc","r5","r3");
}
